from enum import Enum

class RocketMQTags(Enum):
    WHISPER_TASK_FINISHED: "WHISPER_TASK_FINISHED"
    WHISPER_TASK_STATUS_UPDATED: "WHISPER_TASK_STATUS_UPDATED"
    WHISPER_TASK_SUBMITTED: "WHISPER_TASK_SUBMITTED"